import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface GenerateModulesRequest {
  prompt: string;
  courseType?: string;
  targetRole?: string;
  difficultyLevel?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) {
      throw new Error('Gemini API key not configured');
    }

    const { prompt, courseType, targetRole, difficultyLevel }: GenerateModulesRequest = await req.json();

    if (!prompt || prompt.trim().length < 10) {
      return new Response(
        JSON.stringify({ 
          error: 'Please provide a more specific and detailed description for the course modules. For example: "Create modules for an introductory Python programming course covering variables, functions, and basic data structures"' 
        }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        }
      );
    }

    // Build enhanced prompt with context
    const enhancedPrompt = `
You are an expert instructional designer creating course modules for a learning management system.

Context:
- Course Type: ${courseType || 'General'}
- Target Role: ${targetRole || 'General'}
- Difficulty Level: ${difficultyLevel || 'Beginner'}

User Request: ${prompt}

Please generate a structured list of 4-8 course modules based on the request. For each module, provide:
1. Module Name (clear and concise)
2. Module Description (2-3 sentences explaining what learners will achieve)
3. Content Type (text, video, pdf, external_link, or mixed_content)
4. Estimated Duration (in minutes, realistic for the content)
5. Learning Objectives (2-3 specific, measurable outcomes)

Format your response as a JSON array with this structure:
[
  {
    "module_name": "Module Title",
    "module_description": "Detailed description of what this module covers and what students will learn.",
    "content_type": "video",
    "estimated_duration_minutes": 90,
    "learning_objectives": ["Objective 1", "Objective 2", "Objective 3"],
    "suggested_activities": ["Activity or assessment idea"]
  }
]

Guidelines:
- Ensure logical progression from basic to advanced concepts
- Include practical, hands-on activities where appropriate
- Make descriptions engaging and outcome-focused
- Consider the target role and difficulty level in your suggestions
- Ensure content types are appropriate for the material
`;

    console.log('Generating modules with Gemini API...');

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${geminiApiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: enhancedPrompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Gemini API error:', errorData);
      throw new Error(`Gemini API error: ${response.status}`);
    }

    const data = await response.json();
    console.log('Gemini API response received');

    if (!data.candidates || data.candidates.length === 0) {
      throw new Error('No content generated by AI');
    }

    const generatedText = data.candidates[0].content.parts[0].text;
    console.log('Generated text:', generatedText);

    // Try to extract JSON from the response
    let modules;
    try {
      // Find JSON array in the response
      const jsonMatch = generatedText.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        modules = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('No JSON array found in response');
      }
    } catch (parseError) {
      console.error('JSON parsing error:', parseError);
      // Fallback: create a simple module structure from the text
      modules = [{
        module_name: "AI Generated Content",
        module_description: "The AI generated content that needs to be structured into proper modules.",
        content_type: "text",
        estimated_duration_minutes: 60,
        learning_objectives: ["Review AI-generated content", "Structure into proper modules"],
        suggested_activities: ["Manual review and editing"],
        ai_raw_content: generatedText
      }];
    }

    // Validate and clean the modules
    const cleanedModules = modules.map((module: any, index: number) => ({
      module_name: module.module_name || `Module ${index + 1}`,
      module_description: module.module_description || 'AI-generated module description',
      content_type: ['text', 'video', 'pdf', 'external_link', 'mixed_content'].includes(module.content_type) 
        ? module.content_type 
        : 'text',
      estimated_duration_minutes: Math.max(15, Math.min(300, module.estimated_duration_minutes || 60)),
      learning_objectives: Array.isArray(module.learning_objectives) ? module.learning_objectives : [],
      suggested_activities: Array.isArray(module.suggested_activities) ? module.suggested_activities : [],
      module_order: index + 1
    }));

    console.log('Successfully generated', cleanedModules.length, 'modules');

    return new Response(
      JSON.stringify({ 
        success: true,
        modules: cleanedModules,
        originalPrompt: prompt,
        contextUsed: { courseType, targetRole, difficultyLevel }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error in generate-course-modules function:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'An unknown error occurred',
        success: false 
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});